MODEL2_CLASSES = {
    "baked potato", "crispy chicken", "donut", "fries", "hot dog",
    "sandwich", "taco", "taquito", "apple pie", "burger",
    "butter naan", "naan",
    "chai", "chapati", "cheesecake", "chicken curry", "chole bhature",
    "dal makhani", "dhokla", "fried rice", "ice cream", "idli", "jalebi",
    "kaathi rolls", "kadai paneer", "kulfi", "masala dosa", "momos",
    "omelette", "paani puri", "pakode", "pav bhaji", "pizza", "samosa", "sushi",
}

MODEL1_CLASSES = {
    "apple pie", "baby back ribs", "baklava", "beef carpaccio", "beef tartare",
    "beet salad", "beignets", "bibimbap", "bread pudding", "breakfast burrito",
    "bruschetta", "caesar salad", "cannoli", "caprese salad", "carrot cake",
    "ceviche", "cheesecake", "chicken curry", "chicken quesadilla", "chicken wings",
    "chocolate cake", "chocolate mousse", "churros", "clam chowder", "club sandwich",
    "crab cakes", "creme brulee", "croque madame", "cup cakes", "cupcakes",
    "deviled eggs", "donuts", "dumplings", "edamame", "eggs benedict",
    "escargots", "falafel", "filet mignon", "fish and chips", "foie gras",
    "french fries", "french onion soup", "french toast", "fried calamari",
    "fried rice", "frozen yogurt", "garlic bread", "gnocchi", "greek salad",
    "grilled cheese sandwich", "grilled salmon", "guacamole", "gyoza",
    "hot and sour soup", "hot dog", "hummus", "ice cream", "lasagna",
    "lobster bisque", "lobster roll sandwich", "macaroni and cheese", "macarons",
    "miso soup", "mussels", "nachos", "omelette", "onion rings", "oysters",
    "pad thai", "paella", "pancakes", "panna cotta", "papaya salad", "peking duck",
    "pho", "pizza", "pork chop", "poutine", "prime rib", "pulled pork sandwich",
    "ramen", "ravioli", "red velvet cake", "risotto", "samosa", "sashimi",
    "scallops", "seaweed salad", "shrimp and grits", "spaghetti",
    "spaghetti bolognese", "spaghetti carbonara", "spring rolls", "steak",
    "strawberry shortcake", "sushi", "tacos", "takoyaki", "tiramisu",
    "tuna tartare", "waffles",
}

MODELS_12_CLASSES = MODEL1_CLASSES | MODEL2_CLASSES
MODEL1_ONLY_CLASSES = MODEL1_CLASSES - MODEL2_CLASSES
MODEL2_ONLY_CLASSES = MODEL2_CLASSES - MODEL1_CLASSES

CUSTOM_ALL_CLASSES = {
    "allam pachadi", "andhra chicken fry", "andhra fish fry", "apple",
    "aratikaya bajji", "avakaya mango pickle", "bagara rice", "bamboo chicken",
    "banana rasthali", "banana robusta", "banana yelakki", "beerakaya curry",
    "bellam pongali", "bendakaya fry", "bobbatlu", "chalimidi", "chepala pulusu",
    "chintakaya pachadi", "coconut rice", "coffee", "coriander chutney", "corn upma",
    "country chicken fry", "crab masala", "custard apple sitaphal", "dibba rotti",
    "dondakaya fry", "dosakaya curry", "dragon fruit", "dry fruit laddu", "garelu",
    "gongura mutton", "gongura pachadi", "grapes black", "grapes green", "guava",
    "gutti vankaya kura", "jackfruit panasa", "jonna rotte", "kiwi", "kobbari pachadi",
    "kodi vepudu", "lemon", "lemon rice", "majjiga pulusu", "mamidikaya pappu",
    "mango banganapalli", "mango totapuri", "milk", "mirapakaya bajji", "muskmelon",
    "mutton keema curry", "natu kodi pulusu", "orange nagpur", "pachipulusu",
    "palakura pappu", "palathalikalu", "papaya", "pappu charu", "paramannam",
    "peanut chutney", "pear", "perugu annam", "pesara punukulu", "pesarattu",
    "pineapple", "pomegranate", "prawn fry", "pulihora", "punugulu", "ragi sangati",
    "rasam", "rava laddu", "rava upma", "rice", "royyala iguru prawn curry",
    "sakinalu", "sapota chikoo", "sorakaya curry", "strawberry", "sunnundalu",
    "sweet lime mosambi", "tea", "tomato pappu", "ven pongal",
    "watermelon", "adhirasam", "aloo gobi", "aloo matar", "aloo methi",
    "aloo shimla mirch", "aloo tikki", "anarsa", "ariselu", "bandar laddu",
    "basundi", "bhatura", "bhindi masala", "biryani", "boondi", "butter chicken",
    "chak hao kheer", "cham cham", "chana masala", "chapati", "chhena kheeri",
    "chicken razala", "chicken tikka", "chicken tikka masala", "chikki",
    "daal baati churma", "daal puri", "dal makhani", "dal tadka", "dharwad pedha",
    "doodhpak", "double ka meetha", "dum aloo", "gajar ka halwa", "gavvalu",
    "ghevar", "gulab jamun", "imarti", "jalebi", "kachori", "kadai paneer",
    "kadhi pakoda", "kajjikaya", "kakinada khaja", "kalakand", "karela bharta",
    "kofta", "kuzhi paniyaram", "lassi", "ledikeni", "litti chokha", "lyangcha",
    "maach jhol", "makki di roti sarson da saag", "malapua", "misi roti",
    "misti doi", "modak", "mysore pak", "naan", "navrattan korma", "palak paneer",
    "paneer butter masala", "phirni", "pithe", "poha", "poornalu", "pootharekulu",
    "qubani ka meetha", "rabri", "ras malai", "rasgulla", "sandesh", "shankarpali",
    "sheer korma", "sheera", "shrikhand", "sohan halwa", "sohan papdi",
    "sutar feni", "unni appam",
}

CUSTOM_ONLY_CLASSES = CUSTOM_ALL_CLASSES - MODELS_12_CLASSES

# Ensemble: Model 3 top-1 is trusted when it names a class ONLY the custom model has (not in Food-101∪Indian-34).
CUSTOM_EXCLUSIVE_MIN_CONF = 0.85
# After that, Model 1 wins on classes that exist in Food-101 but not in Indian-Western-34 (e.g. spaghetti bolognese).
FOOD101_EXCLUSIVE_MIN_CONF = 0.55
CONSENSUS_THRESHOLD = 0.60
MODEL2_EXCLUSIVE_MIN_CONF = 0.75

LABEL_ALIASES = {
    "fries": "french fries",
    "donut": "donuts",
    "taco": "tacos",
}

HEALTH_WARNING_RULES = {
    "Diabetes": {
        "keywords": [
            "cake","pastry","donut","doughnut","cookie","candy","chocolate","ice cream",
            "ice_cream","jalebi","gulab jamun","gulab_jamun","rasgulla","halwa","kheer",
            "laddu","barfi","mithai","sweet","pudding","brownie","waffle","pancake",
            "french toast","french_toast","muffin","cupcake","cheesecake","pie","tart",
            "bread pudding","bread_pudding","creme brulee","creme_brulee","tiramisu",
            "baklava","macarons","churros","beignets","frozen yogurt","frozen_yogurt",
            "panna cotta","panna_cotta","strawberry shortcake","strawberry_shortcake",
            "red velvet cake","red_velvet_cake","carrot cake","carrot_cake",
            "chocolate cake","chocolate_cake","chocolate mousse","chocolate_mousse",
            "cupcakes","cup cakes","cup_cakes","malapua","modak","bobbatlu","ariselu",
            "adhirasam","imarti","sheer korma","sheer_korma","double ka meetha",
            "double_ka_meetha","ghevar","basundi","rabri","phirni","sheera",
            "sohan halwa","sohan_halwa","shrikhand","misti doi","misti_doi",
            "sandesh","cham cham","cham_cham","ras malai","ras_malai","rasmalai",
            "lyangcha","ledikeni","pithe","chhena kheeri","chhena_kheeri","kalakand",
            "pootharekulu","chalimidi","gavvalu","kajjikaya","shankarpali","poornalu",
            "sunnundalu","chikki","dharwad pedha","dharwad_pedha","anarse",
            "bandar laddu","bandar_laddu","sohan papdi","sohan_papdi",
            "unni appam","unni_appam","sutar feni","sutar_feni","doodhpak",
            "qubani ka meetha","qubani_ka_meetha","chak hao kheer","chak_hao_kheer",
            "kuzhi paniyaram","kuzhi_paniyaram","mysore pak","mysore_pak",
            "rava laddu","rava_laddu","dry fruit laddu","dry_fruit_laddu",
            "paramannam","bellam pongali","bellam_pongali","palathalikalu",
            "lassi","milkshake","soda","cola","soft drink",
        ],
        "message": "This food appears to be high in sugar or refined carbohydrates, which can spike blood glucose levels. People with Diabetes should avoid or consume this in very limited portions. Consider a healthier alternative below.",
    },
    "Obesity": {
        "keywords": [
            "burger","hamburger","hot dog","hot_dog","french fries","french_fries",
            "fried","fry","deep fried","onion rings","onion_rings","nachos",
            "pizza","cheese","creamy","butter","fatty","ice cream","ice_cream",
            "cake","donut","doughnut","chips","mayo","mayonnaise","bacon",
            "sausage","pork","cream","mac and cheese","macaroni and cheese",
            "macaroni_and_cheese","grilled cheese","grilled_cheese",
            "pulled pork","pulled_pork","prime rib","prime_rib","pork chop","pork_chop",
            "foie gras","foie_gras","croque madame","croque_madame",
            "beef carpaccio","beef_carpaccio","beef tartare","beef_tartare",
            "club sandwich","club_sandwich","lobster bisque","lobster_bisque",
            "lobster roll","lobster_roll","crab cakes","crab_cakes",
            "eggs benedict","eggs_benedict","huevos rancheros","huevos_rancheros",
            "poutine","churros","beignets","waffles","pancake","waffle",
            "bread pudding","bread_pudding","baby back ribs","baby_back_ribs",
            "steak","biryani","butter chicken","butter_chicken",
            "dal makhani","dal_makhani","paneer butter masala","paneer_butter_masala",
            "halwa","laddu","mithai","sweet","jalebi","gulab jamun","gulab_jamun",
        ],
        "message": "This food is high in calories, fat, or refined carbohydrates. For weight management, consume rarely and in small portions. Consider a lighter, healthier alternative.",
    },
    "Hypertension": {
        "keywords": [
            "pickle","achaar","papad","chips","namkeen","processed","canned",
            "sausage","bacon","ham","deli","smoked","hot dog","hot_dog",
            "burger","pizza","fast food","soy sauce","fish sauce","ketchup",
            "french fries","french_fries","onion rings","onion_rings",
            "instant","ramen","pho","miso","clam chowder","clam_chowder",
            "lobster bisque","lobster_bisque","french onion soup","french_onion_soup",
            "hot and sour soup","hot_and_sour_soup","crab cakes","crab_cakes",
            "shrimp","prawn fry","prawn_fry","royyala iguru","royyala_iguru",
            "avakaya","mango pickle","mango_pickle","allam pachadi","allam_pachadi",
            "coriander chutney","coriander_chutney","gongura pachadi","gongura_pachadi",
            "chintakaya pachadi","chintakaya_pachadi","kobbari pachadi","kobbari_pachadi",
            "peanut chutney","peanut_chutney",
        ],
        "message": "This food may be high in sodium or salt, which can raise blood pressure. People with Hypertension should limit consumption and opt for low-sodium alternatives.",
    },
    "Heart Disease": {
        "keywords": [
            "fried","deep fried","fry","butter","ghee","cream","creamy","fatty",
            "bacon","sausage","pork","ham","salami","pepperoni",
            "burger","hamburger","hot dog","hot_dog","steak","prime rib","prime_rib",
            "pork chop","pork_chop","baby back ribs","baby_back_ribs",
            "pulled pork","pulled_pork","foie gras","foie_gras",
            "beef carpaccio","beef_carpaccio","beef tartare","beef_tartare",
            "mac and cheese","macaroni_and_cheese","grilled cheese","grilled_cheese",
            "french fries","french_fries","onion rings","onion_rings","chips",
            "pizza","nachos","poutine","croque madame","croque_madame",
            "eggs benedict","eggs_benedict","cake","pastry","donut","doughnut",
            "ice cream","ice_cream","chocolate","butter chicken","butter_chicken",
            "dal makhani","dal_makhani","halwa","laddu","gulab jamun","gulab_jamun",
        ],
        "message": "This food is high in saturated fat, trans fat, or cholesterol, which can negatively impact cardiovascular health. Choose heart-healthy alternatives instead.",
    },
    "PCOD": {
        "keywords": [
            "sugar","sweet","candy","chocolate","cake","donut","doughnut",
            "ice cream","ice_cream","jalebi","gulab jamun","gulab_jamun",
            "rasgulla","halwa","laddu","mithai","fried","deep fried",
            "refined","white bread","pasta","pizza","burger","processed",
            "soda","cola","milkshake","cream","cheesecake","waffle","pancake",
            "french toast","french_toast","maida","macarons","churros","beignets",
            "panna cotta","panna_cotta","tiramisu","baklava",
            "biryani","butter chicken","butter_chicken","dal makhani","dal_makhani",
        ],
        "message": "This food may be high in sugar, refined carbs, or dairy which can worsen hormonal imbalance. Women with PCOD should limit this and prefer low-glycemic, anti-inflammatory alternatives.",
    },
    "Arthritis": {
        "keywords": [
            "fried","deep fried","fry","bacon","sausage","processed","red meat",
            "pork","ham","burger","hot dog","hot_dog","pizza","fast food",
            "sugar","sweet","candy","cake","donut","doughnut","ice cream","ice_cream",
            "alcohol","soda","cola","refined","white bread","chips","nachos",
            "butter","ghee","cream","fatty","saturated","trans fat",
        ],
        "message": "This food may promote inflammation, which can worsen joint pain and stiffness. People with Arthritis should avoid pro-inflammatory foods and prefer anti-inflammatory options like fish, nuts, and leafy greens.",
    },
    "Hyperlipidemia": {
        "keywords": [
            "fried","deep fried","fry","butter","ghee","cream","creamy","fatty",
            "bacon","sausage","pork","ham","salami","pepperoni","lard","shortening",
            "burger","hamburger","hot dog","hot_dog","steak","prime rib","prime_rib",
            "pork chop","pork_chop","baby back ribs","baby_back_ribs",
            "pulled pork","pulled_pork","foie gras","foie_gras",
            "mac and cheese","macaroni_and_cheese","grilled cheese","grilled_cheese",
            "french fries","french_fries","onion rings","onion_rings","chips","nachos",
            "pizza","poutine","croque madame","croque_madame",
            "cake","pastry","donut","doughnut","cookie","brownie","muffin",
            "ice cream","ice_cream","cheesecake","chocolate","whipped cream",
            "butter chicken","butter_chicken","dal makhani","dal_makhani",
            "paneer butter masala","paneer_butter_masala","biryani",
            "halwa","laddu","gulab jamun","gulab_jamun","rasgulla","kheer",
            "creme brulee","creme_brulee","tiramisu","panna cotta","panna_cotta",
            "eggs benedict","eggs_benedict","lobster bisque","lobster_bisque",
            "coconut milk","coconut cream","full fat dairy",
        ],
        "message": "This food is high in saturated fat, trans fat, or cholesterol, which can raise LDL (bad) cholesterol and triglyceride levels. People with Hyperlipidemia should avoid this and choose low-fat, high-fiber alternatives.",
    },
    "Osteoporosis": {
        "keywords": [
            "alcohol","soda","cola","soft drink","energy drink","caffeine",
            "coffee","black tea","salt","sodium","pickle","achaar","papad",
            "chips","namkeen","processed","canned","fast food",
            "high sodium","soy sauce","fish sauce","instant","ramen",
            "chocolate","cocoa","oxalic acid","spinach","beet","rhubarb",
            "liver","organ meat","red meat","fatty meat","bacon","sausage",
        ],
        "message": "This food may interfere with calcium absorption or increase calcium loss from bones. People with Osteoporosis should limit caffeine, high-sodium, and high-oxalate foods, and focus on calcium and Vitamin D rich foods.",
    },
    "Chronic Kidney Disease": {
        "keywords": [
            "salt","sodium","pickle","achaar","papad","chips","namkeen","processed",
            "canned","sausage","bacon","ham","deli","smoked","fast food",
            "soy sauce","fish sauce","ketchup","instant","ramen","miso",
            "banana","orange","potato","tomato","avocado","dates","prunes",
            "nuts","peanut","almond","cashew","walnut","seeds",
            "whole grain","bran","wheat","brown rice","beans","lentil","dal",
            "kidney bean","rajma","chickpea","chana","soybean","tofu",
            "dairy","milk","cheese","curd","yogurt","paneer",
            "red meat","steak","pork","mutton","chicken","fish","seafood","shrimp","prawn",
            "dark chocolate","cocoa","coffee","cola","phosphate","protein shake",
            "supplement","creatine","high protein",
        ],
        "message": "This food may be high in potassium, phosphorus, sodium, or protein — nutrients that must be strictly limited in Chronic Kidney Disease (CKD). Please consult your nephrologist or renal dietitian.",
    },
    "Liver Disease": {
        "keywords": [
            "alcohol","beer","wine","spirits","whiskey","rum","vodka","cocktail",
            "fried","deep fried","fry","butter","ghee","cream","fatty","lard",
            "bacon","sausage","pork","ham","salami","red meat","steak",
            "burger","hamburger","hot dog","hot_dog","pizza","fast food","junk food",
            "cake","pastry","donut","doughnut","cookie","brownie","candy","sweet",
            "ice cream","ice_cream","chocolate","sugar","syrup","halwa","laddu",
            "gulab jamun","gulab_jamun","jalebi","mithai","barfi",
            "chips","nachos","processed","canned","soy sauce","fish sauce",
            "high sodium","salty snack","papad","pickle","achaar",
            "raw shellfish","raw oyster","raw clam","unpasteurized",
        ],
        "message": "This food may burden or damage the liver. People with Liver Disease should avoid alcohol, high-fat, fried, and sugary foods. Focus on lean proteins, fresh vegetables, and whole grains.",
    },
    "Hypothyroidism": {
        "keywords": [
            "soy","soybean","tofu","tempeh","soy milk","edamame","miso",
            "cabbage","broccoli","cauliflower","kale","brussels sprout",
            "bok choy","collard green","radish","turnip","mustard","mustard green",
            "millet","sweet potato","peanut","peanut butter","cassava","tapioca",
            "raw cruciferous","raw kale","raw cabbage","raw broccoli",
            "processed","fast food","refined","white bread","pasta","pizza",
            "sugar","candy","cake","donut","doughnut","cookie","soda","cola",
            "alcohol","caffeine","coffee","gluten","wheat",
        ],
        "message": "This food may contain goitrogens that interfere with thyroid hormone production. People with Hypothyroidism should limit raw cruciferous vegetables, soy-based products, and refined/sugary foods.",
    },
    "Hyperthyroidism": {
        "keywords": [
            "iodine","seaweed","kelp","nori","kombu","wakame","sea vegetable",
            "iodized salt","salty snack","chips","namkeen","seafood",
            "shellfish","shrimp","prawn","crab","lobster","fish","tuna","salmon",
            "dairy","milk","cheese","curd","yogurt","paneer",
            "egg","egg yolk","processed","canned","fast food",
            "caffeine","coffee","black tea","green tea","energy drink",
            "alcohol","sugar","candy","soda","cola","refined",
        ],
        "message": "This food may be high in iodine or stimulants that can worsen an overactive thyroid. People with Hyperthyroidism should avoid iodine-rich foods and stimulants like caffeine and alcohol.",
    },
    "Anemia": {
        "keywords": [
            "coffee","black tea","green tea","tea","caffeine",
            "dairy","milk","cheese","curd","yogurt","paneer","calcium supplement",
            "alcohol","beer","wine","spirits",
            "refined","white bread","pasta","white rice","processed",
            "soda","cola","soft drink","junk food","fast food",
            "oxalic acid","spinach raw","chocolate","cocoa","beet raw",
            "phytic acid","bran","whole wheat","raw legume","raw beans",
        ],
        "message": "This food may block iron absorption or deplete iron stores. People with Anemia should avoid tea, coffee, and calcium-rich foods alongside iron-rich meals.",
    },
    "Gout": {
        "keywords": [
            "red meat","steak","pork","lamb","mutton","beef","veal","organ meat",
            "liver","kidney","heart","brain","sweetbread","offal",
            "seafood","shellfish","shrimp","prawn","crab","lobster","anchovy",
            "sardine","mackerel","herring","tuna","scallop","mussel",
            "alcohol","beer","wine","spirits","whiskey","fructose",
            "sugar","candy","soda","cola","soft drink","fruit juice",
            "high fructose corn syrup","processed","fast food","junk food",
            "bacon","sausage","ham","deli meat","yeast","yeast extract","marmite",
            "asparagus","mushroom","cauliflower","spinach","pea","lentil","bean",
            "dal","rajma","chana","chickpea",
        ],
        "message": "This food is high in purines or fructose which can raise uric acid levels and trigger Gout attacks. Avoid red meat, organ meats, seafood, alcohol, and sugary drinks.",
    },
    "Irritable Bowel Syndrome": {
        "keywords": [
            "gluten","wheat","rye","barley","bread","pasta","pizza","noodle",
            "dairy","milk","cheese","curd","yogurt","paneer","ice cream","ice_cream",
            "lactose","cream","butter","ghee","fried","deep fried","fry","fatty",
            "spicy","chili","pepper","hot sauce","masala","curry","spice",
            "onion","garlic","leek","shallot","spring onion","scallion",
            "apple","pear","peach","mango","watermelon","cherry","fig","date",
            "cashew","pistachio","beans","lentil","dal","chickpea","chana","rajma",
            "soybean","tofu","carbonated","soda","cola","alcohol","caffeine",
            "coffee","black tea","artificial sweetener","sorbitol","mannitol",
            "xylitol","sugar free","diet soda","processed","fast food",
        ],
        "message": "This food may contain high-FODMAP ingredients, lactose, gluten, or gut irritants that can trigger IBS symptoms. Follow a low-FODMAP diet and consult a gastroenterologist.",
    },
    "Gastric Ulcer": {
        "keywords": [
            "spicy","chili","pepper","hot sauce","masala","curry","spice","cayenne",
            "acidic","citrus","lemon","lime","orange","grapefruit","tomato","vinegar",
            "alcohol","beer","wine","spirits","caffeine","coffee","black tea","energy drink",
            "fried","deep fried","fry","fatty","junk food","fast food",
            "processed","canned","sausage","bacon","ham","red meat","steak",
            "chocolate","cocoa","mint","peppermint","carbonated","soda","cola",
            "pickle","achaar","papad","chips","namkeen","salty snack",
            "raw onion","raw garlic","mustard","pepper sauce","hot chutney",
        ],
        "message": "This food is acidic, spicy, or irritating to the stomach lining. People with Gastric Ulcers should avoid spicy, acidic, fried, caffeinated, and alcoholic foods.",
    },
    "Cancer (General)": {
        "keywords": [
            "processed meat","bacon","sausage","ham","salami","pepperoni","hot dog","hot_dog",
            "deli meat","smoked","cured meat","charred","grilled meat","burnt",
            "alcohol","beer","wine","spirits","cigarette","tobacco",
            "fried","deep fried","acrylamide","french fries","french_fries","chips",
            "red meat","steak","pork","lamb","mutton","beef",
            "sugar","candy","soda","cola","soft drink","refined","white bread",
            "fast food","junk food","processed","canned","artificial additive",
            "artificial color","artificial flavor","preservative","nitrate","nitrite",
            "aflatoxin","mold","raw shellfish","raw fish","unpasteurized",
        ],
        "message": "This food has been associated with increased cancer risk. Avoid processed meats, charred foods, alcohol, and highly refined/sugary foods. Focus on a plant-rich, antioxidant diet.",
    },
    "Celiac Disease": {
        "keywords": [
            "wheat","gluten","rye","barley","semolina","maida","atta","whole wheat",
            "bread","pasta","noodle","pizza","cake","pastry","cookie","biscuit",
            "cracker","doughnut","donut","muffin","pancake","waffle","crepe",
            "flour tortilla","chapati","roti","puri","paratha","bhatura","naan",
            "daal puri","kachori","samosa","bread pudding","bread_pudding",
            "soy sauce","malt","malt vinegar","beer","ale","lager","stout",
            "seitan","bulgur","couscous","farro","spelt","kamut","triticale",
            "breaded","breadcrumb","battered","fried with flour","thickened sauce",
            "cream of wheat","malted","malted milk","wheat starch","hydrolyzed wheat protein",
        ],
        "message": "This food contains gluten which causes serious intestinal damage in people with Celiac Disease. Strictly avoid all gluten-containing foods and look for certified gluten-free alternatives.",
    },
    "Lactose Intolerance": {
        "keywords": [
            "milk","dairy","cheese","curd","yogurt","paneer","butter","ghee","cream",
            "ice cream","ice_cream","milkshake","lassi","kheer","basundi","rabri",
            "rasmalai","ras malai","ras_malai","shrikhand","doodhpak","chhena",
            "sandesh","rasgulla","gulab jamun","gulab_jamun","kalakand",
            "misti doi","misti_doi","cham cham","cham_cham","ledikeni","lyangcha",
            "whey","lactose","custard","pudding","bechamel","white sauce",
            "cream soup","creamy","au gratin","paneer butter masala","paneer_butter_masala",
            "dal makhani","dal_makhani","butter chicken","butter_chicken",
            "macaroni and cheese","mac and cheese","cheesecake","pizza","crepe",
        ],
        "message": "This food contains lactose which people with Lactose Intolerance cannot properly digest. Avoid dairy-based foods or choose lactose-free or plant-based alternatives.",
    },
}
